### ISSUE TITLE
Binary strings break (dont)seeInRepository

### ISSUE THREAD

**Issue by frankverhoeven** [Codeception/module-doctrine2#49]
Hi there,

If one of the parameters passed to `(dont)seeInRepository()` is a binary string, the `json_encode` call in `Doctrine2::proceedSeeInRepository()` fails. This results in the following exception: `[JsonException] Malformed UTF-8 characters, possibly incorrectly encoded`. 

Little bit of context. We store UUIDs in a BINARY(16) column. When querying, we select by the binary representation of the UUID .

This was changed in https://github.com/Codeception/module-doctrine2/pull/47, when `JSON_THROW_ON_ERROR` was added to the `json_encode` call. Before it would fail silently and return `false`.

**Comment by Naktibalda** [comment]
I think that we could avoid JSON altogether and show DQL instead of encoded parameters.

https://github.com/Codeception/module-doctrine2/blob/afcf8f4c0f9e3db21f9c6dc6a72f30b114383dec/src/Codeception/Module/Doctrine2.php#L870-L873

Could you test it and raise pull request if it works?

**Comment by frankverhoeven** [comment]
Sure, I'll have a look at it 🙂
