### ISSUE TITLE
[Codecept5] Class "Codeception\Util\ReflectionPropertyAccessor" not found

### ISSUE THREAD

**Issue by yesdevnull** [Codeception/module-doctrine2#51]
**Codeception version:** 5 (alpha-1)
**PHP version:** 8.1.2

```
[Error] Class "Codeception\Util\ReflectionPropertyAccessor" not found
```

The `ReflectionPropertyAccessor` class, which this module depends on, has been removed in Codeception 5. The `doctrine2` method `instantiateAndPopulateEntity()` uses this class to build an entity:

https://github.com/Codeception/module-doctrine2/blob/8f6c868fbda0671f8b1cc3f983ef704b64ea706a/src/Codeception/Module/Doctrine2.php#L520-L533

Unsure how you wish to proceed, so I'll raise this as an issue rather than a PR.

**Comment by Naktibalda** [comment]
oops, that class was unused locally, so I deleted it.

**Comment by Naktibalda** [comment]
I added ReflectionPropertyAccessor to codecept5 branch of this repository.

**Comment by yesdevnull** [comment]
Thanks @Naktibalda, happy for you to close this issue now (I have separately raise #52).
