### ISSUE TITLE
Deleting Entities/Records, `dontHaveInRepository()`?

### ISSUE THREAD

**Issue by blueblakk** [Codeception/module-doctrine2#64]
With `haveInRepository()` we can persist entities, but is there also a way to delete entities/records?

Or are we forced to actually retrieve the entity manager for this and deal with it directly?

**Comment by Naktibalda** [comment]
There is no such method.

I think that more common practice is to use [loadFixtures](https://codeception.com/docs/modules/Doctrine2#loadFixtures) with second parameter set to `false` to reset table to known state.
