### ISSUE TITLE
Depracation notice

### ISSUE THREAD

**Issue by AlexOstrovsky** [Codeception/module-doctrine2#65]
Hello,

I am getting Using ${var} in strings is deprecated, use {$var} instead vendor/codeception/module-doctrine2/src/Codeception/Module/Doctrine2.php on line 974 AND 975

**Comment by Naktibalda** [comment]
Please raise pull request to fix it.

**Comment by AlexOstrovsky** [comment]
@Naktibalda  I checked master and its fixed there. So can you just make new release?
